compucorp/civihr-tasks-assignments

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Task.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
An email notification was not sent to the previous assignee, when the assignee of a task was changed. This PR adds that notification.
=> PCHR-635: Previous assignee is informed when task's assignee is changed.

uk.co.compucorp.civicrm.tasksassignments/api/v3/Task.php
No notification was generated on task deletion. This PR generates notification email for Creator and Assignee when task is deleted.
=> PCHR-550: Notify  assignee and creator on task deletion

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/api/v3/Task.php, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/Footer.tpl
Changed design for Task Delete Notification email.
=> PCHR-550: Email template changes

uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/Footer.tpl
Removed 'get started' text from reminder email footer
=> PCHR-825: Removed 'get started' text from reminder email footer

uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html
In the documents and tasks forms, "Assignment" was mispelled
=> PCHR-632: Fix spelling

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Task.php
A random assignee was appearing in the assignee list of the email that is sent when a task is created.
This additional assignee was coming from the `$previousAssigneeId` whose value was obtained by calling the 'ActivityContact' api filtered by the current task id. The problem was that the call was being made  even if the task was created, not edited (that is, when the task didn't have an id with which we can filter the Activities). As a result the api would return **all** the activities, and the `$previousAssigneeId` value would end up being just the `contact_id` of the first activity whose `record_type_id` value was 1
The api call is now made only if the task has an id. If it has, then it makes sense to look for the previous assignee; if it doesn't, then it means that the task has just …
=> PCHR-862: Random assignee is shown in new task notification email

uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Page/Dashboard.tpl
=> PCHR-1035: Commented code that prints out 'Reports' tab

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Related to https://github.com/civicrm/civihr/pull/976
=> PCHR-1139: Change contact tabs order

uk.co.compucorp.civicrm.tasksassignments/js/karma.conf.js
See https://github.com/civicrm/civihr/pull/1004
=> PCHR-1277: Fix AngularJS tests in CiviCRM 4.7

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
The status present in the emails were incorrect for the document notifications.
This PR fixes those status. 
Before: 
After:
Documents:
Tasks:
=> PCHR-1183: Fixing the status for the document emails

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Original PR : https://github.com/compucorp/civihr-tasks-assignments/pull/79
=> PCHR-1263: ensure hrcase dependency on T&A

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Original PR : https://github.com/compucorp/civihr-tasks-assignments/pull/79
=> PCHR-1263: ensure hrcase dependency on T&A extension

uk.co.compucorp.civicrm.tasksassignments/info.xml
Updating the info.xml file with the lastest value for the `<releaseDate>`,  `<version>`, and `<ver>` fields
=> PCHR-1410: Update info.xml file

uk.co.compucorp.civicrm.tasksassignments/info.xml
Preparing for the 1.6.0 release
=> PCHR-1545: Update CiviHR version and release date and compatibility

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-1545: Update version and release date

uk.co.compucorp.civicrm.tasksassignments/info.xml
Pull requests on this merge:
@davialexandre
- PCHR-1545: Update version and release date for all CiviHR extensions
=> Sync master with staging

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
See [here](https://github.com/civicrm/civihr/pull/1175)
=> PCHR-1584: Improve the loading of tabs' resources

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_forms.scss, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html, uk.co.compucorp.civicrm.tasksassignments/views/directives/sidebar-filters.html
This PR improves the datepicker add-on style.
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
=> PCHR-1524: Datepicker addon style improvement

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-1629: Update extension version and release date

uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.documentList.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html
When trying to access contact task or document tab, the list will not show anything as shown below :
the reason behind this is this commit https://github.com/compucorp/civihr-tasks-assignments/commit/ab63aa58ae6851cede566135b79dab0949a0f425 , some variables inside document-list and task-list controllers are changed but are not changed inside the contact tabs views which caused the issue
I changed the variable names inside the views to match with the associated controllers , I also fixed <uib-pagination> closing tag to match the opening tag .
=> PCHR-1633: Update contact views variables to match the associated controller

uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html
**Requirement:**
In T&A Documents, clicking on target contact was redirecting to assignee, it should be changed to target person.
**Fix:**
Changed URL
=> PCHR-1656: Change contact link

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-1701: Update extensions' version and release date

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-1702: Bump version to 1.6.4

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-1771: Update release date

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-1772: Bump version to 1.6.5

uk.co.compucorp.civicrm.tasksassignments/info.xml
To the 1.6.5 release date, 2017-01-16
=> PCHR-1874: Update release date

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-1947: Bump version

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-1958: Bump version

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_forms.scss, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
For Task, Document modal, header was not present. and modal header text in New assignment need  to be changed form "Create New Assignment" to "New Assignment".
1. Formatted html code with 2 spaced indentatiion.
2. In `views/modal/tasks.html" add modal header for new task.
3. In `views/modal/document.html" add modal header for new document.
4. In `views/modal/addignment.html" modify modal header text.
5. Removed unused styles form `civitasks/partials/_forms.scss`
1. Verified styles changes does not affect other styles using backstopJS scnerios defined in `uk.co.compucorp.civicrm.hrcore` extension.
1. Modal Header in New Task Modal
Before:
After: 
2. Modal Header in New Document Modal
Before:
After:
3. Modal Header text in New Assignment Modal
Before:
After:
1. Failed Tasks: As these …
=> PCHR-1909: Modal header for new task document assignment

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> PCHR-2043: Bump version

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_forms.scss, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html
Label was using heading tag `h2` which resulted in different size of the font in "contact field".
1. To main the consistency of the html markup for field labels, `label` element is used.
2. Added styles for the specific to the label to match with the other label's position in the form.
1. Before:
2. After:
=> PCHR-1927: Contact field update for new assignment

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
Reverts compucorp/civihr-tasks-assignments#169. 
Merged to test e-mail sending on staging, however, it was decided that it would be a better option to enable SMTP to send e-mails on test sites.
=> Revert "PCHR-2051: Send Daily Reminder to Admins Always"

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
Original commits were merged into staging to test e-mails were sent, but reverted later once test sites were configured to send e-mails through SMTP.
Now that the fix has passed testing, the changes have to be replayed on staging branch.
Fix was originally approved on PR compucorp/civihr-tasks-assignments#169
=> PCHR-2051: Replay Commit with Fix on Staging

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Document.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/DocumentTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/TaskTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/DocumentTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TaskTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/bootstrap.php
The tests were not working for a while. This PR aims to fix that.
Tests would fail, initially complaining about missing classes. There were a range of other errors that appears, as well as tests legitimately failing.
All tests run and pass.
- `require_once` lines were causing errors since the file paths were relative and not being found
- Drupal functions, such as `user_load` were not found so I bootstrapped drupal as part of the test bootstrapping.
=> PCHR-2181: Fix Tests

uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js, uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/document.js, uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.js, uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/modal/modal-document_test.js, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html
As per the new wireframe of New Document modal,  newly added fields "Valid From, Document Number and Remind Me" fields needs to be integrated into New Document Modal in Task ad Assignment dashboard. And also update the design of the modal.
Previous design without above mentioned new fields.
1. New Document Modal
New Document Modal with new Design and all three new fields integrated:
1. With Detail Tab 
2. With Assignment tab
1. Details Tab
2. Assignment Tab
Note: This PR is for the subtask of PCHR-2145. So, this is pointing to its parent ticket branch
`PCHR-2145-updates-to-documents` for now. When all sub task will be finished `PCHR-2145-updates-to-documents` will be merged into staging as discussed with @mickadoo .
=> PCHR-2153: Update modal window with new design and adding new fields

.gitignore, package.json
See https://github.com/civicrm/civihr/pull/1930
Also, there was a `.gitignore` file in the repo root that didn't seem to serve any purpose (there is in fact a "real" `.gitignore` in the extension folder), so I removed it
=> PCHR-2303: Improve semistandard hook

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civihr/modules/_unset.scss, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss
I have changed import path for the moved component as per PR: [PCHR-1439: Updates to the theme](https://github.com/compucorp/org.civicrm.shoreditch/pull/14)
---
=> PCHR-1450: Fix numbered list not displayed correctly issue

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js, uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.js, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss
In the last PR #216 `.scss` file was changed but compiled `.css` file was not included in the PR. So, this PR include the compiled `.css` file.
=> PCHR-2323: Issues with remind me text

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> Sync 1.7-wip with la-milestone-3

uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.taskList.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/directives/sidebar-filters.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
As part of this PR, the markup has been updated for `uib-datepicker-popup` inputs.
1. Removed `e-show-calendar-button`, `e-ng-click` attributes.
2. Removed the calendar icon, as it is already added by `uib-datepicker-popup`
---
=> PCHR-2593: Fix other places where datepicker was used

.gitignore, uk.co.compucorp.civicrm.tasksassignments/js/build.js, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Disables debug mode from this extension by only providing minified files, and adds source maps to the build process.
This PR is part of https://github.com/civicrm/civihr/pull/2202
* These were added to the build file for source maps generation:
```js
generateSourceMaps: true,
useSourceUrl: true,
```
* source maps are ignored from being commited.
* only the `js/dist/tasks-assignments.min.js` is provided
There are no tests to run.
=> PCHR-2719: Disable debug mode

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php, uk.co.compucorp.civicrm.tasksassignments/views/settings.html, uk.co.compucorp.civicrm.tasksassignments/xml/Menu/tasksassignments.xml
Contains the following PRs:
* #260 
* #261
=> PCHR-2579: Admin menu updates

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Adding icon to top-level **Tasks** menu item
No icons for top-level Tasks menu item
Icon added to top-level **Tasks** menu item
A new upgrader is added to this extension to set the icon, more details in this PR : https://github.com/civicrm/civihr/pull/2248.
I also fixed the upgrader class indentation so only added the following : https://github.com/compucorp/civihr-tasks-assignments/pull/275/commits/015b3263e3a05e0e3e027ce88bc4785e299e6b89
=> PCHR-2830: Adding icon Tasks top-level menu

uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Page/Dashboard.tpl, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/DailyReminderActivity.tpl, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/DailyReminderActivityOthers.tpl, uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.documentList.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html, uk.co.compucorp.civicrm.tasksassignments/views/settings.html
This PR simply swaps any occurrence of the word "Assignment" with the word "Workflow" throughout the extension
=> PCHR-2637: Replace assignment with workflow

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Similar to this PR https://github.com/civicrm/civihr/pull/2289 but for this extension.
=> PCHR-2830: Replacing fa class for menu item icons with crm-i

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Task.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TaskTest.php
Some test related changes to get the CiviHR client pingback test working
CiviHR pingback tests did not work
All CiviHR tests using T&A code pass
---
=> PCHR-2599: Ping back

uk.co.compucorp.civicrm.tasksassignments/info.xml
Bump the version number to 1.7.3
=> PCHR-3232: Bump version number

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
This PR updates the role names to the new names after the changes made in [ #435](https://github.com/compucorp/civihr-employee-portal/pull/435)
The role names were not updated.
The role names are updated in files that are still using the old name for the updated roles.
=> PCHR-3071: Update Role names

package-lock.json, package.json
See https://github.com/civicrm/civihr/pull/2473
=> PCHR-3246: Implement stylelint for SASS files

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_lists.scss, uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/taskMigrate.html
The PR(and https://github.com/compucorp/org.civicrm.shoreditch/pull/84, https://github.com/compucorp/civihr-employee-portal-theme/pull/315) fixes the T&A Admin styles.
Select dates with no tasks assigned , See blank table without any notifications
Select dates with no existing key dates, See blank table without any notifications
Select dates with no documents assigned, See blank table with headers and no notifications
Similarly text is shown in Documents and Key Dates
1. No Result Text added to `dashboard/documents.html`, `dashboard/key-dates.html` and `dashboard/tasks.html`.
2. Also added margin top to `partials/_lists.scss` to provide enough space on of top no result text.
Click 'Add workflow' button, See that Key Date field is highlighted with red as if it was wrong
In …
=> PCHR-3061: Task and Assignment admin styles

uk.co.compucorp.civicrm.tasksassignments/info.xml
Bumping extension versions to 1.7.4 in preparation for this month's release.
=> PCHR-3318: Bump version to 1.7.4

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
Currently the daily reminder emails go to recipient without active contracts and to emails that are not the primary work emails of the recipients. This PR fixes this issue and makes sure that only recipients with active contracts get daily reminder emails and such emails goes to the primary work email of the recipient, if both criteria are not met, i.e recipient has an active contract and has a primary work email, the email us not sent to such a recipient even if it satisfies other criteria.
- The daily reminder email goes to recipient without active contracts and to emails that are not the primary work emails of the recipients.
This is due to the fact that the two queries for getting recipients that is merged together via a [UNION](https://github.com/compucorp/civihr-tasks-assignments/blo …
=> PCHR-3382: Send Daily reminder Email to Recipient With Active Contract and With Primary Work Email

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
This fixes issues reported in the QA for the configuration menu changes
One of the labels was incorrect
'Workflows' is now 'Workflow Types'
=> PCHR-3299: QA Fixes

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civihr/_civihr.scss, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks.scss
This PR fixes contact view page and makes solution with flexbox to make it of equal height with flexbox
This PR removes unwanted css based no changes done at 
https://github.com/compucorp/org.civicrm.shoreditch/pull/103
- BackstopJS tested
- Only shoreditch repository is rested with stylelint, civihr and task repository is not tested with stylelint due to time constrains on mainstream project.
=> NDI-73: Fix contact view page for handling tabs with flexbox

Jenkinsfile
See https://github.com/civicrm/civihr/pull/2579 for details
=> PCHR-3592: Add slack notifications to Jenkins #2579

uk.co.compucorp.civicrm.tasksassignments/info.xml
Update release date and bump version to 1.7.6
=> PCHR-3638: Bump ext version

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks.scss, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_shoreditch-imports.scss
This PR syncs styles with Shoreditch. Please see https://github.com/compucorp/org.civicrm.shoreditch/pull/110 for more info. Also please see https://github.com/civicrm/civihr/pull/2644 for the technical implementation as it is essentially the same in this PR.
----
According to the dist CSS file diff, there are no style changes whatsoever **except the mobile datepicker**.
=> PCHR-3724: Sync styles with Shoreditch

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
For proper grouping of case type into categories, custom field need to be setup. This PR creates upgrader for setting up custom field with option values  `Workflow and Vacancy`.
There was no custom group and field relating to case types.
New custom group (`Case Type Category`) and custom field (`Category`) was setup with options workflow and vacancy for categorization. 
Creating the custom fields automatically setup the two options (`workflow and vacancy`) for since the the `html_type` for the custom field is `Select`.
```php
private function _createCustomField() {
civicrm_api3('CustomField', 'create', [
'custom_group_id' => 'case_type_category',
'label' => 'Category',
'name' => 'category',
'data_type' => 'String',
'html_type' => 'Select',
'is_required' => 1,
'column_name' => 'category', …
```
=> PCHR-3836: Add Upgrader for Case Type Custom Field

package-lock.json, uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/karma.conf.js, uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/karma.conf.js
See https://github.com/compucorp/civihr/pull/2772 for details
=> PCHR-3942: Fix paths to org.civirm.reqangular files

package-lock.json, package.json
See https://github.com/compucorp/civihr/pull/2828 for overview
0 vulnerabilities left
Things done:
1. Removed unused [`gulp-sass-bulk-import`](https://github.com/mathisonian/gulp-sass-bulk-import)
2. Updated to karma v3
=> PCHR-4046: Fix security vulnerabilities

uk.co.compucorp.civicrm.tasksassignments/info.xml, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
This PR contains the changes made in the Menu management improvements epic.
It contains the following PR's
PCHR-4222: #427
=> PCHR-4182: Menu Management Improvements

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> CiviHR 1.7.12

uk.co.compucorp.civicrm.tasksassignments/info.xml
=> CiviHR 1.7.13

package-lock.json
=> PCHR-4494: Update dependencies
