compucorp/civihr-tasks-assignments

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/MyDocuments.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/MyTasks.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/xml/Menu/tasksassignments.xml
Changed the links form screenshot below to link to redirection page, that directs user to Tasks and Assignments, or to SSP if they don't have permissions to access TA.
A small change in SSP is required (adding ID's to "Tasks" and "Documents" sections), ~~which I will send in another PR shortly~~ linked below.
This PR requires: https://github.com/compucorp/civihr-employee-portal/pull/89
=> PCHR-434: Added redirections to 'my documents' and 'my tasks'

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
Issue: 
Keydates sections was not displaying all keydates
Solution:
Fetch all keydates irrespective of contactID
=> PCHR-554: show all keydates for next 7 days in reminder email

uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
This is the same *gulpfile* fix described in [this PR](https://github.com/civicrm/civihr/pull/868) , only applied to the _civihr-tasks-assignments_ repo
=> PCHR-858: Add error handling in build process in gulpfile

uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/taskMigrate.html
The ui.select library is throwing errors now that we have moved to AngularJS v.15 ([PCHR-870](https://github.com/civicrm/civihr/pull/871)). This seems kind of a big (recurrent?) issue for the library which currently still have to be addressed
There is a (seemingly working) workaround to this, which consists in applying to the directive tags same-named classes:
```html
<ui-select-match class="ui-select-match"...>
<ui-select-choices class="ui-select-choices" ...>
```
for some reason this works, and so I have gone through every place where the directive is used and implement those classes manually
=> PCHR-879: Issue with ui-select with AngularJS v1.5

uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
Adding more informations (id, status, creation date, subject) to the Assignment lookup select dropdown, to make it work similar to the "File to Case" feature in default CiviCRM
=> PCHR-637: Add more information to the Assignment lookup select dropdown

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/Reminder.tpl
When a task is assigned from a person to another, the old assignee is listed in the "Assignee" list alongside the new one, making harder to tell which one is which
The previous assignee is now displayed separately from the new one
Also the `sendReminder` static method has been refactored (the focus was kept still on the scope of the ticket, so no parts of the code unrelated to the issue were changed) into smaller methods.
One noteworthy change was how the activity contact's emails were fetched. Before it was done with two api calls:
```php
$contactResult = civicrm_api3('Contact', 'get', array(
'return' => 'display_name',
'id' => array('IN' => $value['ids']),
));
$emailResult = civicrm_api3('Email', 'get', array(
'return' => 'contact_id,email',
'contact_id' => array('IN' => $value['ids']), …
```
=> PCHR-635: Original assignee is not distinct from the new assignee

uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/run.js, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Page/Documents.tpl, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Page/Tasks.tpl
The "Tasks" and "Documents" tabs in the Contact page weren't loading. The former appeared to be stuck in a loading loop, the latter just didn't show anything
There were two issues that caused the bug:
1. We moved the t&a app from `ngRoute` to `ui.router` ([commit](https://github.com/compucorp/civihr-tasks-assignments/commit/770dea1112a177cf99599c21929af25a12fa17fd)) but forgot to change the `ng-view` directive into `ui-view` in the documents and tasks templates
2. The `textAngular` angular module was causing problems, which were fixed by using the version store in the `common/` dependencies and by [this PR](https://github.com/civicrm/civihr/pull/890)
=> PCHR-901: Task and Documents tab on Contact page are stuck in a loading loop

uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html
Addressing the same issue as #35, but this time for 'add new document' modal.
Adding more informations (id, status, creation date, subject) to the Assignment lookup select dropdown, to make it work similar to the "File to Case" feature in default CiviCRM
=> PCHR-637: Fix 'add to assignment' in documents modal.

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
We need to disable the menu items of the Case extension (`org.civicrm.hrcase`) when Tasks&Assignments is enabled.
To be sure this change is retroactive, an upgrader has been written as well
=> PCHR-573: Assignment menu links need to be cleaned up

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks.scss, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_custom-select.scss, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
As a quickfix before the ui-select dropdown is properly customized, in case where the directive is used just as a standard select dropdown (that is, single value without the search/filter functionality enabled), then the directive is removed and a normal custom-style select element (`.crm_custom-select`) is used
Since the T&A extension is still not using the common style and since .crm_custom-select is defined in there, then as a quick fix the `.crm_custom-select` is redefined as a local partial in the extension (ugly fix, for we can't wait until we make the full swap to using the common style)
=> PCHR-772: Swap lookup directive for normal select dropdown

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civihr/modules/_select.scss
The `ui-select` directive can be used as a [angular-xeditable](https://vitalets.github.io/angular-xeditable/) field, meaning that the `z-index` of all the different elements ("follow link" links, action buttons, dropdown list, etc) can be in conflict with one another.
The dropdown list however should always be on top of all the other elements, so its `z-index` has been increased
=> PCHR-853: Increase z-index of ui-select dropdown list

uk.co.compucorp.civicrm.tasksassignments/.editorconfig
Adding a [.editorconfig](http://editorconfig.org/) file to standardize coding style for all the project's developers/contributors
=> PCHR-1022: Adding .editorconfig file to repo

uk.co.compucorp.civicrm.tasksassignments/api/v3/Assignment.php
Using CRM_Case_BAO_CaseContact class if CRM_Case_BAO_Case::addCaseToContact method is not available.
CRM_Case_BAO_CaseContact is a new class which comes in CiviCRM 4.7 while CRM_Case_BAO_Case::addCaseToContact is CiviCRM 4.5 / 4.6 method which we were originally using when developing the extensions.
=> PCHR-1043 - missing CRM_Case_BAO_Case::addCaseToContact() method

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php, uk.co.compucorp.civicrm.tasksassignments/xml/Menu/tasksassignments.xml
The "Tasks and Assignments" main menu item and the "Tasks" and "Assignments" tabs in the contact page were visible and accessible even if the user didn't have the "access Tasks and Assignments" credentials assigned to it
Also, the `access_arguments` values weren't specific enough for some of the pages defined in `tasksassignments.xml`
In the `tasksassignments_civicrm_tabs` hook, the tabs are added only if the user has the credential
```php
function tasksassignments_civicrm_tabs(&$tabs) {
if (CRM_Core_Permission::check('access Tasks and Assignments')) {
$tabs[] = Array(/* ... */);
}
```
The upgrader function that adds the T&A main menu item (`upgrade_0002`) has been amended so that it sets the permission correctly on it, but to be sure that the change is applied retroactively, a new …
=> PCHR-1075: Fix permissions

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Document.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Task.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/Api/DocumentTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/Api/TaskTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/DocumentTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/TaskTest.php
Task / Document entities were handling creation logic the same way as original Activity entity so these three contact fields were not required on API level when creating an entity instance. I've modified both BAOs to require these contacts IDs when creating a new entity instance.
=> PCHR-1160 - Making 'source_contact_id', 'target_contact_id' and 'assignee_contact_id' required fields when creating Task / Document on BAO level.

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Both **hrcase** and **Tasks & Assignments** Extensions try to create the following case types ( Joining , Exiting ) , but since there is a unique constraint on case type name field in civicrm_case_type table this is not possible and many errors arisen which is reported here  PCHR-1151 and later on here  PCHR-1191 .
After starting a discussion on the later one we decided to remove these case types from **Tasks & Assignments** extension since these case types are related to HR , and in case **Tasks & Assignments** is used with civihr then hrcase have to be enabled too.
=> PCHR-1191: Remove joining & exiting case types from T&A extension

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Linked PR : https://github.com/civicrm/civihr/pull/1020
The user should not be able to uninstall/disable T&A in case hrcase extenstion is enabled.
I've checked if hrcase is installed and enabled inside both  **tasksassignments_civicrm_uninstall** and **tasksassignments_civicrm_disable** hooks so if it is  installed and enabled the user will be redirected to extensions manager page and an error notification will appear informing the user to uninstall/disable hrcase extension first .
=> PCHR-1263: ensure hrcase dependency on T&A

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Page/Dashboard.tpl
**Before**
**After**
Also now the T&A extension, when enabled, will *always* remove the "Cases" main menu item, while before it was done only when `hrcase` was already enabled ("Cases" does not really belong to `hrcase`, but rather to CiviCRM in general, so there's no use in making that distinction based on `hrcase`).
The original upgrader was renamed as to be the newest  (i tested it and it doesn't seem to create any problem the fact that there is a "hole" between upgrades)
=> PCHR-1477: Remove the "Assignments" tab and the "Cases" top nav item

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civihr/.gitignore, uk.co.compucorp.civicrm.tasksassignments/scss/civihr/modules/_config.scss, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_dashboard.scss
This PR remove the top padding from `#ct-dashboard` selector, and it was reverted `_config.scss` file to be able to generate CSS.
***Before***
***After***
=> PCHR-1476: Remove top padding

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
We were using dummy data for the document types values:
* Joining Document 1
* Exiting Document 1
They are not being replaced by real, default values:
* VISA
* Passport
* Government Photo ID
* Driving licence
* Identity card
* Certificate of sponsorship (COS)
=> PCHR-1364: Delete dummy document types and add real ones

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Assignment.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/AJAX.php, uk.co.compucorp.civicrm.tasksassignments/phpunit.xml.dist, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/AssignmentTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/TasksassignmentsTestTrait.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/bootstrap.php, uk.co.compucorp.civicrm.tasksassignments/xml/Menu/tasksassignments.xml
When trying to search in  (add to assignment) box , it was not showing any result and a the following error appear in the console  :
```"Error in resource configuration for action `query`. Expected response to contain an array but got an object (Request: GET `/index.php?q=civicrm/case/ajax/unclosed)"```
The reason behind this is the deletion of this ajax end-point **civicrm/case/ajax/unclosed** in civicrm 4.7 and  a new quick-form method created **addEntityRef** to replace it . (https://github.com/civicrm/civicrm-core/commit/abd06efc426540ed16cb091093f90e13df2579f1)
since we are working with angular and **addEntityRef** cannot be used since it is a quick-form method , I restored the **civicrm/case/ajax/unclosed** and the callback method **unclosedCases** in T&A extension.
So now the …
=> PCHR-1527: Fix add to assignment input when adding documents

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Document.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/api/v3/Document.php, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/DailyDocumentsNotification.tpl, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/Document.tpl
Created 'senddocumentnotification' API action and BAO logic + Upgrader function installing daily scheduled job.
The new API action sends daily email notifications for documents including separate lists with:
- Overdue documents (!= approved)
- Due in next fortnight (14 days) (!= approved)
- Due in < 90 days (!= approved)
And show status in email.
Acceptance criteria:
- Emails are sent out to assignees only.
- Assignee contact receives lists of documents he/she is assigned to only
- Documents are grouped by due date according to the logic described in the task description
An exaple of email with documents notifications:
=> PCHR-1362 - Email notifications for documents

uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.js, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html
This PR removes the 'set status' option from document status dropdown and uses the "_ui-select_" dropdown, with the "_allow-clear_" option.
Before:
After:
This PR is related to: https://github.com/civicrm/civihr/pull/1130
=> PCHR-1322: Removing "set status" option from document status dropdown

uk.co.compucorp.civicrm.tasksassignments/info.xml
After the 2016-11-03 release, additional fixes had to be added to the 1.6.3 release.
Since this is not a public release yet, it was decided we should move the tag
instead of applying hotfixes. That is why we need to rever the version and
updated the release date here.
=> PCHR-1701: Revert CiviHR version

uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html
**Problem:** 
Task count on tabs are not updated when switched between filters. 
The counters should show the actual number of tasks below it.
**Fix:** 
Applying `filterByDue` and `filterByStatus`to Documents and `filterByDue` to Tasks on the main `list` array to filter.
Before
After
=> PCHR-1630: Apply proper filters

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Related PR : https://github.com/civicrm/civihr/pull/1276
T&A should not create and default activity type , hrcase extension should do that instead .
I removed the upgrader that creates these activity types.
=> PCHR-459: Remove the creation of default activity types

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/DAO/Assignment.php
Expected behaviour for 'get' API call to Assignments entity in front-end required it to return an array of contacts for each assignment found, however, this was not happening. As it turned out, Assignments entity is based on CiviCRM Case entity, and this contact array is only included in results if a case ID is passed as parameter on API call.  However, CiviCRM wasn't able to identify the ID field for the Assignments entity appropriately, expecting it to be either 'id' or 'assignment_id', which never happened, since it was actually 'case_id', as Assignments DAO was a direct extension of Case BAO.
Fixed the problem by creating 'id' field in Assignment's DAO, by altering the fields array defined in Case DAO and copying values for 'case_id' and changing its key to 'id'.
=> PCHR-1872: Fix Error on T&A Calendar View

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
**Problem:**
The daily email digest goes out to all creators (civihr_admin) and assignees (could be civihr_admin/civihr_manager/civihr_staff) of tasks/docs that are overdue/due today/coming up this week. Creators see both tasks/docs created and delegated by them. Assignees see only tasks/docs they are supposed to work on.
Need to use different destination urls depending on user having access civicrm permission.
**Solution:**
Check the contact id loading corresponding drupal user for access permission "access CiviCRM" , if it has access than the email link should point to civicrm else it should link to dashboard.
=> PCHR-1904: Changing activity URL depending upon contact id permissions.

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/KeyDates.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/KeyDates.php
Contacts deleted to trash still appear on key dates. They should not. 
API Call to KeyDates Entity 'get' function returned dates associated to contacts in trash can, since the is_deleted field was not taken into account when building the query.  Fixed by adding 'is_deleted = 0' to all queries used to obtain key dates.
=> PCHR-1888: Remove Deleted Contacts' Info From Key Dates

uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
The Due Date and Expity Date fields were not wide enough, resulting in the date value being trimmed
Shortening the label and adjusting the grid cells solved the problem
=> PCHR-1908: Fix dates fields width in task/document modal

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/AJAX.php, uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civihr/modules/_select.scss, uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
_(Related to https://github.com/civicrm/civihr/pull/1592)_
This PR has changes related to the upgrade of the `ui.select` library
The assignment lookup dropdown is fetching the data from a backend endpoint, which was returning the id of the assignment as a number, not as a string. This caused a problem with the newer version of ui-select, as the dropdown was using the id as a string to find the currently selected assignment in the assignments list. Forcing the id to be a string solves the issue
```php
foreach ($unclosedCases as $caseId => $details) {
$results[] = array(
'id' => "{$caseId}",
```
The T&A is not yet using the common theme, and as such it has a local copy of the ui-select css. Given that the library has been updated, the css needs to be updated as well
We have a custom theme …
=> PCHR-1912: Upgrade ui.select

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civihr/partials/_forms.scss, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_forms.scss, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html
The input placeholder's and ui-select-placeholder's color needed to be changed to `#999999`.
1. Add new color as scss variable  and override ui-select-placeholder existing color.
2. Maintain the color of the selected and chosen values as previously available.
1. Before 
2. After
=> PCHR-1911: Placeholders colors in new task and assignment modal

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
Daily digest with notifications should be sent to administrators always, with upcoming and overdue tasks, key dates and appraisals.  However, there wasn't a functionality implemented to send reminders to civihr_admin users.
Added functionality that obtains contact ID's for users with administrator and civihr_admin roles, and includes them in the query used to obtain contact list to which to send daily digest.
=> PCHR-2051: Send Daily Reminder to Admins Always

uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html, uk.co.compucorp.civicrm.tasksassignments/views/directives/sidebar-filters.html
The date fields in filters in T&A dashboard currently are small and needs to increase their width little longer to display full date.
Add replace `col-lg-7` by `col-lg-8`  in each date field's container in  following files:
1. `uk.co.compucorp.civicrm.tasksassignments/views/directives/sidebar-filters.html`
2. `uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html`
1. In Tasks:
2. Key Dates:
=> PCHR-2088: Increased Date fields width in T&A dashboard

uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
Currently `col-sm-6` is used which only takes  six columns  resulting to display the subject field as half-width.
Add `col-sm-12` instead of `col-sm-6` for subject field container.
=> PCHR-1910: Make subject field in New Task modal to full-width

uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.taskList.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html
A) Pencil icons were missing form 
1. uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html and 
2. uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.taskList.html
Note: Similar is the case with tasks list in contact page.
B) The "Created By: ..." block in task is kept inside the task details block  both in task list in contact page and calendar tasks list page, 
Which does not match with the task in T&A dashboard as follows:
B) Subject field is not consistent with T&A dashboard tasks in calendar task list and contact task page.
1. Add pencil icons in appropriate editable fields in the above files.
2. Display subject field if no data for subject is  present.
3. Adjust bootstrap grid to display subject editable field in same line.
1. Displays pencil icons and …
=> PCHR-2103: Make task list consistent in contact calendar tasks and in dashboard

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html
Using the [org.civicrm.shoreditch](https://github.com/civicrm/org.civicrm.shoreditch) theme would cause a misalignment in the tasks list in the assignments modal
This was caused by the entire rows to have the `.required` class, that would match the `.crm-container .required` selector in the new theme, which finally would add the red * that would misalign the table
The `required` class wasn't required anyway on the rows, so it has been removed thus fixing the problem
The temporary partial for the ui-select dropdown (see #172 ) contained a reference to the shoreditch theme, which was incorrect, as by using the values contained in the shoreditch theme would change the colors of the dropdown. The right reference is to the old theme instead (`org.civicrm.bootstrapcivicrm`)
=> PCHR-2064: Changes for adopting shoreditch theme

uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/taskMigrate.html
When you click any select dropdown in new task or new assignment or new document modal you cannot start typing search queries immediately, you need to click the field again.
It's a problem on the library it self, the problem is related with `ngAnimate`, if we remove `ngAnimate` it works.
- https://github.com/angular-ui/ui-select/issues/1592
- https://github.com/angular-ui/ui-select/issues/1436
- https://github.com/angular-ui/ui-select/issues/1201
As a temporary solution until the library fix it, it was added the directive [prevent-animations](https://github.com/civicrm/civihr/blob/staging/org.civicrm.reqangular/src/common/directives/prevent-animations.js) to remove the animation on ui-select elements.
**Before**
**After**
=> PCHR-1913: Fix ui-select first-click focus

.github/PULL_REQUEST_TEMPLATE.md, .gitignore, CONTRIBUTING.md
Adds a pull request template.
Each creator of a pull request defined their own structure for the description.
This template will be used as a suggested format for the description.
To see what the PR template looks like now check [here](https://github.com/civicrm/civihr/blob/PCHR-2159-pull-request-template/.github/PULL_REQUEST_TEMPLATE.md)
---
=> PCHR-2159: Add Pull Request Template

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/DAO/Document.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/api/v3/Document.php, uk.co.compucorp.civicrm.tasksassignments/xml/activity_custom_fields.xml
Adds three new fields for documents
- Valid from
- Document Number
- Remind Me
The only custom fields for documents were expire_date and merge_date.
The three new fields will be added and available in the API explorer.
The new document fields were added manually and exported using `civix generate:custom-xml --data=14`. I added the new fields to the existing XML since existing fields will be ignored.
It was decided that all existing documents should have "remind me" set to true, so I've added an upgrader for this.
Originally "document number" was due to be called "document ID" but since this clashes with the actual ID field I changed it.
This PR targets PCHR-2145 branch as it is part of a larger ticket which will be tested as a whole when all subtickets are complete.
---
I do not have …
=> PCHR-2151: New Fields for Documents

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Document.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/api/v3/Document.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/DocumentTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/TaskTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/DocumentTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TaskTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/bootstrap.php
The functionality for cloning documents that are approaching their expiry date is already developed and in use. After adding the "remind me" column in #189 we need to check before cloning if the user has selected that they want to be reminded about the document before cloning it.
All documents that had an expiry date soon approaching were cloned.
Only documents with "remind me" set to true will be cloned (if their expiry date is approaching).
- Originally I had to unset all the custom field names (there are 3 variations for each e.g. `expire_date`, `custom_77` & `custom_77_9`) before creating but by using "return" in the get request it limits the field names.
- I tried to tidy up by removing raw SQL usage
---
=> PCHR-2152: Remind Me Functionality

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
For installations that started prior to v1.6.2 when they ran the upgrader it would have executed code to add ActivityTypes. However in v1.6.2 this upgrader number was re-purposed to add a setting for tasks and assignments. This setting is missing in staging and production sites, so it appears that this upgrader was skipped. This PR will re-run the upgrader and ensure the setting is created.
The setting does not exist. If you go to /civicrm/tasksassignments/settings#/ and try to change the "Number of days before Document's expire date when a Document clone should be created:" setting it will appear to have worked, but reloading the page will show it to still be empty.
The setting will exist in the option_value table. You will be able to store the number of days value in …
=> PCHR-2216: Redo Upgrade To Add Option Value

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
The original plan for the document update ticket was to set "remind me" to true for all existing documents in the database. This is failing on staging so will be removed from the release.
The updater would set "remind_me" to be true for all existing document
"remind_me" will not be set for existing document
This is failing on staging because of a timeout. On further investigation it seems the chained API call is creating 2 extra revisions for each document every time it fails. This is a combination of expected behavior (the Activity creation will create a revision) and some bug in our document API code which is also creating another revision. These should be fixed separately, see [PCHR-2227](https://compucorp.atlassian.net/browse/PCHR-2277).
---
=> PCHR-1945: Remove updating of custom document values

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
Sending the daily reminder gathers a list of tasks and key dates that should be included in the e-mail. It's possible, however, that a contact can be selected because they're involved in a key date (their birthday, for example) but because of the logic for deciding who can see key date data they would receive an empty e-mail.
There is no check to see if there is any data to send in the email and it's possible to send empty mails.
There is a check before sending if there is actually any content for the mail.
---
Unfortunately tests were fixed in PCHR-2145-updates-to-documents and this is still waiting to be merged.
=> FAR-182: Empty Reminder Emails

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
'Tasks and assignments Daily Reminder' job is being installed in a disabled state by default. Requirements for PCHR-1687 state this job should be enabled by default on new CiviHR installations. 
Changed the is_active flag on job creation.
---
=> PCHR-1687: Enable Tasks and Assignments Daily Reminder Job

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Implementing 'hook_civicrm_tabset' instead of 'hook_civic…rm_tabs' as it's deprecated in CiviCRM 4.7.
=> PCHR-1604 - Update extensions to use hook_civicrm_tabset instead of hook_civicrm_tabs

uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js, uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.js, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss
In T&A document modal, when clicked help icon next to remind me, a pop up is displayed with information. The information had some typos and link for `here` was missing, this PR addresses those issues.
1. Replace (only fixed words are listed)
```js
$scope.remindMeMessage = "... reviewed ... types..."
```
with 
```js
$scope.remindMeMessage = "... renewed ... <a target='_blank' href='/civicrm/tasksassignments/settings#/'>here</a>... type ..."
```
2.  SInce the `civihr-ui-select.scss` files no longer exists in `org.civicrm.shoreditch` extension, the `civihr-ui-select` should be reused form `org.civicrm.bootstrapcivihr` extension. So the following updates needs to be done.
Replace
```js
@import "../../../../../org.civicrm.shoreditch/scss/bootstrap/components/civihr-ui-select/civihr-ui-select"; …
```
=> PCHR-2323: Issues with remind me text

uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js, uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/document-list.js, uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/main.js, uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.js, uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/document-list_test.js, uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/modal/modal-document_test.js, uk.co.compucorp.civicrm.tasksassignments/js/test/services/document_test.js, uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.documentList.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html
When admin edits existing document from civi (T&A) - the modal title is 'New document', which is confusing. The title needs to  be changed to be "Edit document".
1. `modalDocument()` in `uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/main.js` needs to be updated to accept the mode the document modal should be opened.
```js
$rootScope.modalDocument = function (modalMode, data, e) {
...
modalMode = modalMode || 'new';
data = data || {};
var modalInstance = $modal.open({
appendTo: $rootElement.find('div').eq(0),
templateUrl: config.path.TPL + 'modal/document.html?v=3',
controller: 'ModalDocumentCtrl',
resolve: {
modalMode: function () {
return modalMode;
},
...
}
});
}
```
2. Use `modalMode` and create a `modalTitle` variable to store the modal title based on …
=> PCHR-2319: Change the modal title to edit document in civi

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js, uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.js, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html
The multiple select of document status in T&A is broken displaying the dropdown bar in the field. This PR removes the  dropdown bar specific to the field.
1. Added `no-dropdown` attribute in ui-select element in `uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html`
```html
<ui-select ... no-dropdown>
```
2. Now add style to hide the dropdown bar in `uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss` file.
```css
// Do not display dropdown for ui-select-multiple with attribute no-dropdown
[no-dropdown].ui-select-multiple {
&:after {
display: none;
}
}
```
1. The modal Controller is being reused in SSP as well. Since the SSP does not have the notification as in T&A, the `var notification = CRM.alert(...)` will be undefined resulting …
=> PCHR-2317: Remove dropdown bar for multiple select in sidebar in T&A

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Document.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Assignment.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Document.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/DocumentTest.php
Every time the Clone documents batch job is executed, it adds redundant clones of the expiring document record.
Cloning scheduled job was copying all revisions of a document that met cloning criteria, which resulted in duplicates being created each time the job was run. Even though cloned documents were being marked as such, this marking was done on a new revision of the document. Thus, the old revision always met the cloning criteria. The problem was even worse if an approved document was changed, as this would create even more revisions, that would also get cloned.
Fixed by only cloning current revisions of a document, if they meet other cloning criteria.
---
=> PCHR-2414: Only Clone Current Revision of a Document

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Document.php, uk.co.compucorp.civicrm.tasksassignments/api/v3/Document.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/DocumentTest.php
Updating a document sometimes created one or two revisions. It should behave the same way as activities, only creating revisions if it is set to a case.
The implementation of create API call to Documents entity was generating up to two revisions per call, when the following conditions were met:
- Params array contained 'case_id'
- Params array contained a custom field
This happened because, first, Document create API generated a new revision from the document's old data, if a value for 'case_id' was found in params array, making any updates on the new revision after. Once the initial updates were done, it checked if there were any custom fields being updated, and if
so, made an API call to Activity's create action to update the document's custom fields. This call also checks for case_id …
=> PCHR-2277: Don't Create Extra Revisions on Document Updates

uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html, uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
This PR adds the "class markers" to avoid the [enable-select2.js](https://github.com/civicrm/org.civicrm.shoreditch/blob/master/js/enable-select2.js) and [radio-checkbox.js](https://github.com/civicrm/org.civicrm.shoreditch/blob/master/js/radio-checkbox.js) scripts to the marked radio/select elements, that was resulting in broken styles
---
=> PCHR-2464: Additional post-amnesty-merge fixes

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
This PR updates the menu structure of the T&A extension
=> PCHR-2610: Update T&A menu structure

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php, uk.co.compucorp.civicrm.tasksassignments/views/settings.html, uk.co.compucorp.civicrm.tasksassignments/xml/Menu/tasksassignments.xml
1. The PR amends the structure of the "Configure" menu, moving the content of "Configure > People Management" submenu under "Configure > Tasks"
2. Also, in https://github.com/compucorp/civihr-tasks-assignments/pull/260 i forgot to update the "Configure > Settings" label, this PR takes care of that
1.  <img width="350" alt="before" src="https://user-images.githubusercontent.com/6400898/31188898-d3033634-a936-11e7-9ad5-f00f4a9a5eaf.png">
2. The label was "Configure > Settings"
1.  <img width="350" alt="after" src="https://user-images.githubusercontent.com/6400898/31188908-d8abe86a-a936-11e7-96f2-6c85a94502ab.png">
2. The label is "Configure > Tasks Settings"
=> PCHR-2611: Rename 'Settings' to 'Tasks Settings'

uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/directives/sidebar-filters.html
After adding fix in PR #245 and in course of adopting angular js style guide, there left few regression issues causing the filters in tasks broken:
issues:
1. https://github.com/compucorp/civihr-tasks-assignments/pull/245/files#diff-9ddc2c346e6840e0dfe2f4c8d2217fb3R96
2. https://github.com/compucorp/civihr-tasks-assignments/pull/245/files#diff-d034a1547714f392d984ef97994dd244R34
3. https://github.com/compucorp/civihr-tasks-assignments/pull/245/files#diff-d034a1547714f392d984ef97994dd244R48
This PR fixes those introduced/unnoticed issues both in `/tasks` and `/documents`
1. The task filters were broken.
2. Filtering the tasks when clicking the tabs in `/tasks` not working with correct counter value.
1. The tasks filters work properly.
2. Filtering the tasks when clicking the tab in …
=> PCHR-2753: Tasks filter by date doesn't work on 1.6 and 1.7

uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/modal/modal-document.spec.js, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html
This PR fixes the issue being all tasks and filter section gets expanded and collapsed on clicking "show more" label in each task in T&A tasks dashboard.
- Expands and collapses all tasks:
1. Use "isCollapsed" property from Task controller. Currently its using of Task List controller.
```html
<div class="row">
<div class="col-xs-12">
<a href ng-click="isCollapsed = !isCollapsed" class="btn btn-collapse">
<span class="fa" ng-class="{fa: true, 'fa-chevron-down': !isCollapsed, 'fa-chevron-right': isCollapsed }" aria-hidden="true">
</span>
Show More
</a>
</div>
</div>
<article class="row" uib-collapse="isCollapsed">
....
</article>
```
- Not required
=> PCHR-2999: Toggle collapsing of specific task

uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html, uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.taskList.html
This PR fixes the following issues with Tasks in the contact section and calendar:
* When clicking "Show More" all tasks would expand or collapse at the same time.
* When Clicking on "Resolved" a "No results found." would always be displayed regardless of the tasks displayed.
* Note: the resolved panel stops working after opening it for the first time.
To fix the "Show More" issue the `list.isCollapsed` was changed to a local variable per task: `isCollapsed`. This avoids collapsing all tasks at the same time.
To fix the Resolved tasks the proper variable name was `listResolved` instead of `list.listResolved`:
```html
<div class="alert alert-danger" ng-show="list.listResolvedLoaded && !listResolved.length">No results found.</div>
```
BackstopJS tests were run successfully
---
=> PCHR-3058: Fix tasks list issues

uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Page/Documents.tpl, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Page/Tasks.tpl
As part of https://github.com/civicrm/civihr/pull/2374, all the tabs Contact Profile page having `container` class, has been changed to `container-fluid`. This PR updates the same for Tasks and Documents.
Replaced `container` with `container-fluid`, and the css styles are applied from https://github.com/compucorp/org.civicrm.shoreditch/pull/75. No visual change has happened.
=> PCHR-2919: Fix responsiveness

uk.co.compucorp.civicrm.tasksassignments/CRM/Activity/Service/ActivityService.php, uk.co.compucorp.civicrm.tasksassignments/api/v3/Task.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TaskTest.php
In [this commit](https://github.com/compucorp/civihr-tasks-assignments/commit/6ce23f327ab4986714aa40dc2d22ea0ee9f43e0a) the existing code was refactored to reduce repetition. However the `record_type_id` was not preserved, which meant that all requests that used the `source_contact_id` would instead search for tasks with that assignee ID.
Requests to Task.get filtering by `source_contact_id` would instead return tasks with assignees with the given `source_contact_id`.
Filtering by `source_contact_id` will return Tasks with that source contact ID. 
---
=> PCHR-3171: Fixing Task Get Filter

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
With no tasks or document reminders to be set the changes in #169 meant that admins were always added to the list of recipients. However the [method](https://github.com/compucorp/civihr-tasks-assignments/pull/169/files#diff-11a08f8d66984202e4167d6d1176103cR361) to get the Admin contact IDs actually returns Drupal user IDs.
By changing this to return admin contact IDs the admins will receive an email with the key dates, regardless if there are no task / document reminders.
`_getAdminContactIds` returned a list of Drupal user IDs with `civihr_admin` or `administrator` roles. In cases where there are no other task or document reminders the key dates alone will not be sent since this method will return a list of Druapl user IDs which will fail the check for …
=> PCHR-3050: Replace Drupal user IDs with CiviCRM contact IDs

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/gulpfile.js, uk.co.compucorp.civicrm.tasksassignments/js/karma.conf.js, uk.co.compucorp.civicrm.tasksassignments/package.json
This PRs adds the necessary changes in order for Jenkins to run the T&A tests.
Jenkins couldn't run the extension's tests
Jenkins can run the extension's tests. The same way as it works for CiviHR, it will run the tests in these specific scenarios:
- a PR has the `ready to test` label
- a merge is merged to `staging` or `master`.
Notifications are sent when a build starts, fails and/or finishes. Since we don't have a specific room for the T&A project on hipchat, they will be sent to the CiviHR room.
The Jenkinsfile added here was heavily based on the [CiviHR one](https://github.com/civicrm/civihr/blob/staging/Jenkinsfile). However, since we have a single extension to be tested here, all the code related to looping through a list of extensions was removed.
T&A is supposed to be a …
=> PCHR-3105: Run T&A tests with Jenkins

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
This PR sets custom field groups that should not be editable to "is_reserved"=yes for the following custom groups.
- Activity Custom Fields
- Probation
=> PCHR-3353: Set Custom Groups to Reserved

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
This PR changes the help text for the Workflow Create and Edit screen.
The CiviCRM's [alterAngular hook](https://docs.civicrm.org/dev/en/latest/framework/angular/changeset/) was implemented so it changes the workflow's help text:
```php
// modifies the workflow's edit.html template:
function tasksAssignments_civicrm_alterAngular(\Civi\Angular\Manager $angular) {
$changeSet = \Civi\Angular\ChangeSet::create('Workflow Modifications');
$changeSet->alterHtml('~/crmCaseType/edit.html', function (phpQueryObject $doc) {
_tasksAssignments_civicrm_alterAngular_change_workflow_help_text($doc);
});
$angular->add($changeSet);
}
// changes the help text:
function _tasksAssignments_civicrm_alterAngular_change_workflow_help_text(phpQueryObject $doc) {
$text = '<p>' . ts('paragraph #1') . '</p>';
$text …
```
=> PCHR-3040: Change the Workflow help text

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
This PR removes tabs that are not relevant to CiviHR from the Workflow configuration. These tabs are:
* Workflow roles,
* Workflow statuses, and
* Activity types.
The alter angular hook was used to remove the tabs defined in the workflow configuration screen:
```php
function tasksAssignments_civicrm_alterAngular(\Civi\Angular\Manager $angular) {
$changeSet = \Civi\Angular\ChangeSet::create('Workflow Modifications');
$changeSet->alterHtml('~/crmCaseType/edit.html', function (phpQueryObject $doc) {
_tasksAssignments_change_workflow_help_text($doc);
_tasksAssignments_remove_non_civihr_tabs_from_workflow($doc); // <--- here
});
$angular->add($changeSet);
}
function _tasksAssignments_remove_non_civihr_tabs_from_workflow (phpQueryObject $doc) {
$tabs = ['roles', 'statuses', 'actType'];
foreach …
```
=> PCHR-3402: Remove non relevant tabs from the Workflow configuration screen

uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
This PR fixes the following issues:
* Replaces the actions dropdown with a single button for the "Add timeline" action.
* Moves the help text outside of the case type form.
The CiviCRM's alter angular hook was implemented in order to replace the dropdown:
```php
function tasksAssignments_civicrm_alterAngular(\Civi\Angular\Manager $angular) {
$changeSet = \Civi\Angular\ChangeSet::create('Workflow Modifications');
$changeSet->alterHtml('~/crmCaseType/edit.html', function (phpQueryObject $doc) {
_tasksAssignments_change_workflow_help_text($doc);
_tasksAssignments_remove_non_civihr_tabs_from_workflow($doc);
_tasksAssignments_allow_only_add_timeline_action($doc); // <--- here
});
$angular->add($changeSet);
}
function _tasksAssignments_allow_only_add_timeline_action (phpQueryObject $doc) { …
```
=> PCHR-3403: Allow only the "Add timeline" action

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
We are changing what menu items can be accessed. T&A provides some items for the "Configure" submenu, and these will be altered.
- T&A provided the "Tasks" submenu in the "Configure" menu but no items had permission set
- It cloned two items from the CiviCase submenu, which were relabled as "Workflows" and "Workflows Status"
- The weight of the "Tasks" item was not set and so it appears at the top of the list
- The permission for all T&A menu items is `administer CiviCase`. 
- The "Workflows Status" menu item is no longer cloned. 
- The weight of "Tasks" has been set so it appears in the required order (before "Leave")
=> PCHR-3376: Update T&A Administer Menu Items

uk.co.compucorp.civicrm.tasksassignments/info.xml
This includes:
- Bumping the version number
- Setting the develStage to `stable`
- Updating maintainer
- Updating extension name (a more complete update will be done in another chance)
- Removing placeholder text
=> PCHR-3481: Bump version to 1.7.5

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/Options.php
As part of this PR the Reserved Activity Types are hidden from the UI.
I am showing the count of Option Values for the Screenshots only. Its not part of the code.
1. In `uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/Options.php`,
- Overriding `browse` function to hide `is_reserved` option values.
=> PCHR-3416: Hide reserved activity types

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
This PR renames the following workflow statuses:
|From|to|
|----|--|
|Ongoing|In Progress|
|Resolved|Completed|
A new upgrader was added to T&W:
```php
<?php
class CRM_Tasksassignments_Upgrader extends CRM_Tasksassignments_Upgrader_Base
{
// ...
public function upgrade_1032() {
$this->_renameCaseStatus('Ongoing', 'In Progress');
$this->_renameCaseStatus('Resolved', 'Completed');
return TRUE;
}
private function _renameCaseStatus($fromLabel, $toLabel) {
$optionValue = civicrm_api3('OptionValue', 'getsingle', [
'option_group_id.name' => 'case_status',
'label' => $fromLabel,
'is_reserved' => 1,
'options' => [ 'limit' => 1 ],
]);
civicrm_api3('OptionValue', 'create', [
'id' => $optionValue['id'],
'label' => $toLabel
]);
}
}
```
=> PCHR-3405: Rename workflow statuses

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Task.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Case.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/CaseType.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/OptionGroup.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/OptionValue.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/api/v3/Task.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/TaskTest.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TaskTest.php
This PR automatically closes cases when all of its child tasks have been completed successfully. This is only true for cases of the "Workflow" category (see [this PR](https://github.com/compucorp/civicrm-core/pull/15) for more information about workflow categories).
A new check was added when updating tasks to determine if the parent case can be closed:
```php
public static function create(&$params) {
// ...
if ($hook === 'edit') {
$isWorkflowCaseCategory = 'WORKFLOW' === self::getCaseCategory($instance->case_id);
$allCaseTasksAreCompleted = self::checkIfTasksBelongingToCaseAreCompleted($instance->case_id);
if ($isWorkflowCaseCategory && $allCaseTasksAreCompleted) {
self::markCaseAsClosed($instance->case_id);
}
}
}
private static function getCaseCategory($caseId) {
if (empty($caseId)) { …
```
=> PCHR-3571: Mark case as closed

package-lock.json
Unfortunately the fix in #352 didn't work, due to the `package-lock.json` file not being updated correctly, thus not making the warning disappear
The problem appears to be on whether `hoek` is listed as a 1st-level property in the lock file: if it is, then GitHub will display the warning. The instructions mentioned in the previous PR are meant to fix this problem, basically resulting in a diff containing this change:
For some reason the lock file in the previous PR, although changed, didn't contain that particular changes, and thus the problem was not fixed.
Running the instructions again
```bash
npm install hoek && npm uninstall hoek && npm update && npm i 
```
resulted in the lock file contained in this PR, which should fix the issue.
Sanity checks that I've run before submitting the …
=> PCHR-3635: Fix for #352

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Form/Options.php, uk.co.compucorp.civicrm.tasksassignments/js/CRM/Form/Options.js
This PR makes the following changes to the "Add Activity" modal on the activity types configuration screen:
* It renames the modal title to "Add New Task / Document Type".
* It renames the "Component" field to "Category".
* It only displays "Tasks" and "Documents" in the "Category" options.
* It moves the "Category" field to the top of the form
The code that makes all the changes reads as follows:
```php
public function buildQuickForm() {
parent::buildQuickForm();
// Changes the title of the modal:
CRM_Utils_System::setTitle('Add New Task / Document Type');
// Adds the "Tasks" and "Documents" options to the "Category" dropdown:
$categoryOptions = array();
$civiTaskId = CRM_Core_Component::getComponentID('CiviTask');
$civiDocumentId = CRM_Core_Component::getComponentID('CiviDocument');
if …
```
=> PCHR-3418: Modify the "Add Activity" modal

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
This PR adds a new menu item for Activity Types under the tasks administration menu. 
A new upgrader was added:
```php
public function upgrade_1037() {
civicrm_api3('Navigation', 'create', [
'label' => 'Activity Types',
'name' => 'activity_types_administer',
'url' => 'civicrm/admin/options/activity_type?reset=1',
'permission' => 'administer CiviCase',
'parent_id' => 'tasksassignments_administer',
'is_active' => 1,
]);
return TRUE;
}
```
This task is about adding a new menu item, not replacing/moving the old one under `Configure > Customize Data and Screens > Activity Type`
=> PCHR-3700: Add Activity Type menu item

uk.co.compucorp.civicrm.tasksassignments/gulpfile.js, uk.co.compucorp.civicrm.tasksassignments/js/tasks-assignments.build.js, uk.co.compucorp.civicrm.tasksassignments/js/tasks-notification-badge.build.js
This PR https://github.com/compucorp/civihr-tasks-assignments/pull/363 introduced an error in the `build.js` file that resulted in the `tasks-assignments.min.js` file not being generated by the build process anymore.
The problem was that a `build.js` file cannot contain multiple configuration objects, as the RequireJS optimizer will only read and use the last object it finds in the file
```js
({
baseUrl : 'src',
out: 'dist/tasks-assignments.min.js',
name: 'tasks-assignments',
skipModuleInsertion: true,
},{
baseUrl : 'src',
out: 'dist/tasks-notification-badge.min.js',
name: 'tasks-notification-badge',
skipModuleInsertion: true,
})
```
as a result, given that the configuration object for the `tasks-notification-badge` module was last, only that module was being built in the build process, …
=> PCHR-3769: Fix build process

Jenkinsfile
The ownership of the civihr repository has been transferred from the CiviCRM organization to Compucorp. This PR updates references to the repo URL to reflect the new ownership.
URLs to the repository would reference `civicrm` as the owner.
URLs to the repository now reference `compucorp` as the owner.
=> PCHR-3811: Update the civihr repo URL

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Set default number of days before document expiry when the clone document should be created = 90 days
If this field is blank, update it to 90 days.
There was an Upgrader function "upgrade_1020" that was setting default days before document expiry to 0.
The new Upgrader function "upgrade_1038" is setting the default number of days to 90 if it is empty or equals to zero. And the existing upgrader  "upgrade_1020" was changed to set default number of days to 90.
=> PCHR-3543: Update T&A Settings

package-lock.json, package.json, uk.co.compucorp.civicrm.tasksassignments/gulpfile.js, uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/karma.conf.js, uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/karma.conf.js, uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/karma.conf.js
See https://github.com/compucorp/civihr/pull/2727 for details
There are 3 test suites in T&A, and they were all ran in parallel
```js
all: function () {
runServer('crm-tasks-workflows/karma.conf.js')
runServer('tasks-assignments/karma.conf.js');
runServer('tasks-notification-badge/karma.conf.js');
},
```
which lead to a confusing console output, where the suites results would overlap each other.
Making sure that the test suites are instead ran in sequence improves the readability of the output
```js
all: function () {
runServer('crm-tasks-workflows/karma.conf.js')
.then(function () {
runServer('tasks-assignments/karma.conf.js');
})
.then(function () {
runServer('tasks-notification-badge/karma.conf.js');
});
},
```
=> PCHR-3926: Add karma spec reporter to JS unit tests

Jenkinsfile, uk.co.compucorp.civicrm.tasksassignments/CRM/Activity/Form/ActivityView.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Assignment.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/api/v3/TASettings.php, uk.co.compucorp.civicrm.tasksassignments/settings/tasksandassignments.setting.php, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TASettingsTest.php
This PR is part of https://github.com/compucorp/civihr/pull/2720 and updates Tasks and Assignments so that it can be used with CiviCRM 5.3.0. It includes fixes for things that stopped working after the upgrade, syncing of overridden files and some minor fixes not related to the upgrade. See "Technical Details" for more information.
The extension could not be used with CiviCRM 5.3.0
The extension can be used with CiviCRM 5.3.0
This extension has its own API to save and fetch settings: `TASettings`. Internally, this API would use Option Values to store the settings. That is, each setting was an Option Value in the `ta_settings` Option Value, and the value was the setting value. Whenever a setting was updated, the Option Value value was updated as well. Because of that, it was possible to …
=> PCHR-3429: CiviCRM upgrade

Jenkinsfile, uk.co.compucorp.civicrm.tasksassignments/CRM/Activity/Form/ActivityView.php
This PR include a couple of small updates to make CiviHR compatible with CiviCRM 5.3.1:
- The `Jenkinsfile` was updated to run the tests using CiviCRM 5.3.1 (a 5.3.1 patches branch was also created in our fork of civicrm-core)
- Overridden files were synced
=> PCHR-4008: CiviCRM 5.3.1 upgrade

uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
For `crm-tasks-workflows` module, RequireJS cannot be used, added a detailed comment explaining why.
=> PCHR-3941: Add doc for crm-tasks-workflows build process

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
This PR moves the creation of the case type category field back to Tasks and Assignment. The upgrader was first moved to HRCore in this PR https://github.com/compucorp/civihr/pull/2799 in order to fix case categorization on test sites, but the upgrader did not work as intended.
What has been tested both on local sites and test sites is to have the upgrader for creating the custom field in Tasks and Workflow, and leave the case type categorization on HRCase as intended by the previous PR.
```json
{
"is_error": 0,
"version": 3,
"count": 3,
"values": [
{
"id": "8",
"title": "Application",
"custom_100022": "Vacancy",
"is_forkable": "1",
"is_forked": "1"
},
{
"id": "18",
"title": "Exiting",
"custom_100022": "Workflow",
"is_forkable": "1",
"is_forked": ""
},
{
"id": "19",
"title": "Joining", …
```
=> PCHR-4050: Move back upgrader for creating case type category field

Jenkinsfile
See https://github.com/compucorp/civihr/pull/2853
Note: The failure in this PR is not caused by this change. It was introduced by https://github.com/compucorp/civihr-tasks-assignments/pull/385, but because the threshold was wrong when the PR was merged, we didn't catch the failure. https://github.com/compucorp/civihr-tasks-assignments/pull/420 will fix it.
=> PCHR-4166: Set Jenkins failure threshold to 0

uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css, uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss
See https://github.com/compucorp/civihr/pull/2912. The T&A stylesheet too has some ad-hoc style for the select2 dropdown, and that too was the cause for the regression issues
_("before" is above, "after" is below)_
_(the before screenshots are taken with the fork synced but without the regression issues fixes)_
**Single select2, closed**
The vertical alignment of both the "down" caret and the X icon is improved
**Single select2, open**
The additional icon is removed, and the "up" caret is now of the same font size and with the same horizontal alignment of the "down" caret
**Multiple select2, closed**
The vertical alignment of the text and the position of the icon is now fixed
**Multiple select2, open**
No major changes
=> PCHR-4356: Fix regression issues when syncing with latest Shoreditch release

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/DashboardSwitcher.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/MyDocuments.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/MyTasks.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php, uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TASettingsTest.php
This PR fixes all links in T&A that include AngularJS routing parameters. Links broke due to upgrade of AngularJS to version `1.7` (see https://github.com/compucorp/civihr/pull/2790).
This PR also has a child PR here https://github.com/compucorp/civihr/pull/2953.
We simply replace all the occurrences of `[^/]#/` to `$1#!/` (basically adding an `!` after the hash symbol as per AngularJS 1.6+.
Please note, we do **not** replace all the occurrences or `#/` because some of them is CiviCRM, for example: `civicrm/a/#/caseType`.
-----
✅Manual Tests - passed
⏹Jasmine Tests - not needed
⏹JS distributive files - not needed
⏹CSS distributive files - not needed
⏹Backstop tests - not needed
⏹PHP Unit Tests - not needed
=> PCHR-4243: Fix AngularJS 1.6 router links

Jenkinsfile, uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
This PR is part of the updates to make CiviHR compatible with CiviCRM 5.7.0. The other part of the work was done in https://github.com/compucorp/civihr/pull/2899.
In CiviHR, we use `hook_civicrm_tabset` in multiple extensions to make sure the tabs in the Contact page will be displayed in some specific order. This order mandates that the "Documents" tab should be displayed after the "Communications" (activities, internally). However, due to a [recent cleanup](https://github.com/civicrm/civicrm-core/pull/12941) in CiviCRM core, the order of these two items was inverted after upgrading to 5.7.0. The reason is that after the cleanup, the "Communications" tab now has a [hardcoded weight of 70](https://github.com/colemanw/civicrm-core/blob/42e8679229d13e5112002a888075ed4b4d156057/CRM/Contact/Pag …
=> PCHR-4346: CiviCRM Upgrade

uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/Footer.tpl, uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/Reminder.tpl
This PR fixes URLs and augments labels for buttons in the T&A email notifications.
The links are broken, the button label for admin is wrong (should be "See all...") and the link for the staff (assignee) does not make any sense, they would probably not have access to `/civicrm...` at all (unless the assignee is admin).
Please note the URLs in the left bottom corner.
The labels and URLs are now fixed. Please note the URLs in the left bottom corner.
Also, the email header link URL has been fixed for Assignees (it was earlier leading to `/civicrm...`). We left the URL as is for the Creators.
We define if an email is sent to assignee or not:
```php
$isAssignee = array_search($contactId, $activityContacts['assignees']['ids']) !== FALSE;
```
Then, based on the flag above, we define URLs and …
=> PCHR-4363: Fix tasks and documents email notifications buttons URLs
